# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c89f7c88b34052ed5b8f88d67481cd2de8a53c28a1d9cb81fda7492cff08920678d8927447c864410712c0187a301f5cca53c7fbb1f6e321f5ad82d642c3cb54

test:
  secret_key_base: 999c3e772996be354daa4253794619394c49be2b5e5c41e1e946ab8d8f7ada293729bae6aaf5534258be3008501b4c8665c54f5cb5c6f2c89c19ab7138f977b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
